In [222]:
import numpy as np

In [223]:
# 1. Matrixin satır ve sütun sayısı alınır
while True:
    satir1 = int(input("İşlem için kullanılacak 1. Matrixin satır sayısını giriniz: "))  
    if satir1 > 0:  
        break
    else:
        print("Lütfen 0'dan büyük bir sayı giriniz!")  
while True:
    sütun1 = int(input("İşlem için kullanılacak 1. Matrixin sütun sayısını giriniz: "))  
    if sütun1 > 0:  
        break
    else:
        print("Lütfen 0'dan büyük bir sayı giriniz!") 

İşlem için kullanılacak 1. Matrixin satır sayısını giriniz:  6
İşlem için kullanılacak 1. Matrixin sütun sayısını giriniz:  6


In [224]:
# 1. Matrix oluşturuluyor
matrix1 = []
for i in range(satir1):
    dizi1 = []
    for j in range(sütun1):
        dizi1.append(np.random.randint(10, 99))  
    matrix1.append(dizi1)  
matrix1 = np.array(matrix1)

In [225]:
# 2. Matrixin satır ve sütun sayısı alınır
while True:
    satir2 = int(input("İşlem için kullanılacak 2. Matrixin satır sayısını giriniz: "))  
    if satir2 > 0:  
        break
    else:
        print("Lütfen 0'dan büyük bir sayı giriniz!")  

while True:
    sütun2 = int(input("İşlem için kullanılacak 2. Matrixin sütun sayısını giriniz: "))  
    if sütun2 > 0:  
        break
    else:
        print("Lütfen 0'dan büyük bir sayı giriniz!") 

İşlem için kullanılacak 2. Matrixin satır sayısını giriniz:  6
İşlem için kullanılacak 2. Matrixin sütun sayısını giriniz:  6


In [226]:
# 2. Matrix oluşturuluyor
matrix2 = []
for i in range(satir2):
    dizi2 = []  
    for j in range(sütun2):
        dizi2.append(np.random.randint(10, 99))  
    matrix2.append(dizi2)  
matrix2 = np.array(matrix2)

In [227]:
# Oluşan matrixleri yazdırma
print("Random Oluşan 1. Matrix : ")
print(matrix1)
print("Random Oluşan 2. Matrix : ")
print(matrix2)

Random Oluşan 1. Matrix : 
[[35 77 11 80 94 28]
 [41 40 82 58 23 31]
 [53 33 88 64 69 91]
 [16 64 38 57 83 61]
 [62 35 96 30 60 58]
 [85 80 11 77 27 85]]
Random Oluşan 2. Matrix : 
[[52 22 89 90 37 46]
 [76 83 58 33 52 19]
 [90 31 38 64 50 11]
 [45 94 89 83 26 30]
 [56 33 72 91 68 61]
 [96 64 73 88 41 69]]


In [228]:
# Matrix toplama fonksiyonu
def matrixToplam(matrix1, matrix2): 
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        print("Matrix boyutları uyuşmadığından, matrixler arasında toplama işlemi yapılamaz")
    else:
        toplamMatriks = matrix1 + matrix2
        print("Matriksler Toplamı : ")
        print(toplamMatriks)

In [229]:
# Matrix çıkarma fonksiyonu
def matrixCıkarım(matrix1, matrix2): 
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        print("Matrix boyutları uyuşmadığından, matrixler arasında çıkarma işlemi yapılamaz")
    else:
        farkMatriks = matrix1 - matrix2
        print("Matriksler Farkı : ")
        print(farkMatriks)

In [230]:
# Matrix transpozunu alma fonksiyonu
def matrixTranspozu(matrix1):
    satir = len(matrix1)         
    sutun = len(matrix1[0])   
    
    transpoz = [[0] * satir for _ in range(sutun)]
    
    for i in range(satir):
        for j in range(sutun):
            transpoz[j][i] = matrix1[i][j]
    
    print("Matrisin transpozu alınmış hali: ")
    print(np.array(transpoz))

In [231]:
# Matrix çarpımı fonksiyonu
def matrixCarpim(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Matrix çarpımı için uygun değillerdir")
    else:
        carpim = [[0] * len(matrix2[0]) for _ in range(len(matrix1))]
        for i in range(len(matrix1)):  # A'nın satırları
            for j in range(len(matrix2[0])):  # B'nin sütunları
                for k in range(len(matrix2)):  # A'nın sütunları ve B'nin satırları
                    carpim[i][j] += matrix1[i][k] * matrix2[k][j]
        
        print("Matrixler çarpımı:")
        print(np.array(carpim))

In [232]:
# Fonksiyonları çağırma
matrixToplam(matrix1, matrix2)  # Matrixlerin toplamını yazdır

Matriksler Toplamı : 
[[ 87  99 100 170 131  74]
 [117 123 140  91  75  50]
 [143  64 126 128 119 102]
 [ 61 158 127 140 109  91]
 [118  68 168 121 128 119]
 [181 144  84 165  68 154]]


In [233]:
print("1. Matrixin transpozu : ")
matrixTranspozu(matrix1)  # 1. Matrixin transpozunu yazdır

1. Matrixin transpozu : 
Matrisin transpozu alınmış hali: 
[[35 41 53 16 62 85]
 [77 40 33 64 35 80]
 [11 82 88 38 96 11]
 [80 58 64 57 30 77]
 [94 23 69 83 60 27]
 [28 31 91 61 58 85]]


In [234]:
print("2. Matrixin transpozu : ")
matrixTranspozu(matrix2)  # 2. Matrixin transpozunu yazdır

2. Matrixin transpozu : 
Matrisin transpozu alınmış hali: 
[[52 76 90 45 56 96]
 [22 83 31 94 33 64]
 [89 58 38 89 72 73]
 [90 33 64 83 91 88]
 [37 52 50 26 68 41]
 [46 19 11 30 61 69]]


In [237]:
matrixCarpim(matrix1, matrix2)  # Matrixlerin çarpımını yazdır

Matrixler çarpımı:
[[20214 19916 23931 24053 15469 13260]
 [19426 14959 18166 19893 12040  8830]
 [28664 20750 27282 31090 18164 16441]
 [22185 18843 22082 23636 15447 13352]
 [24802 15757 22420 25933 16152 13135]
 [24627 22420 27625 27322 15178 15373]]


In [238]:
matrisCıkarım(matrix1,matrix2) 

Matriksler Farkı : 
[[-17  55 -78 -10  57 -18]
 [-35 -43  24  25 -29  12]
 [-37   2  50   0  19  80]
 [-29 -30 -51 -26  57  31]
 [  6   2  24 -61  -8  -3]
 [-11  16 -62 -11 -14  16]]
